version: "3.1"
name: lofty-shop

services:
    mongo:
        container_name: mongo
        image: mongo
        restart: always
        environment:
            - MONGO_INITDB_DATABASE:interview
            - MONGO_INITDB_ROOT_USERNAME:root
            - MONGO_INITDB_ROOT_PASSWORD:password
        ports:
            - 27017:27017

    mongo-express:
        container_name: mongo-express
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINPASSWORD:password
            - ME_CONFIG_MONGODB_ADMINUSERNAME:root
            - ME_CONFIG_MONGODB_URL:mongodb://root:password@mongo:27017/
        depends_on:
            - mongo
