export const APPOINTMENTS_GET_REQUEST = "APPOINTMENTS_GET_REQUEST"
export const APPOINTMENTS_GET_SUCCESS = "APPOINTMENTS_GET_SUCCESS"
export const APPOINTMENTS_GET_FAIL = "APPOINTMENTS_GET_FAIL"
export const APPOINTMENTS_GET_CLEAR = "APPOINTMENTS_GET_CLEAR"

export const APPOINTMENTS_CREATE_REQUEST = "APPOINTMENTS_CREATE_REQUEST"
export const APPOINTMENTS_CREATE_SUCCESS = "APPOINTMENTS_CREATE_SUCCESS"
export const APPOINTMENTS_CREATE_FAIL = "APPOINTMENTS_CREATE_FAIL"
export const APPOINTMENTS_CREATE_CLEAR = "APPOINTMENTS_CREATE_CLEAR"

export const APPOINTMENTS_DELETE_REQUEST = "APPOINTMENTS_DELETE_REQUEST"
export const APPOINTMENTS_DELETE_SUCCESS = "APPOINTMENTS_DELETE_SUCCESS"
export const APPOINTMENTS_DELETE_FAIL = "APPOINTMENTS_DELETE_FAIL"
export const APPOINTMENTS_DELETE_CLEAR = "APPOINTMENTS_DELETE_CLEAR"

export const APPOINTMENTS_DATE_REQUEST = "APPOINTMENTS_DATE_REQUEST"
export const APPOINTMENTS_DATE_SUCCESS = "APPOINTMENTS_DATE_SUCCESS"
export const APPOINTMENTS_DATE_FAIL = "APPOINTMENTS_DATE_FAIL"
export const APPOINTMENTS_DATE_CLEAR = "APPOINTMENTS_DATE_CLEAR"
