export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGIN_CLEAR = "LOGIN_CLEAR"

export const LOGIN_NOTIFICATION = "LOGIN_NOTIFICATION"
export const LOGIN_NOTIFICATION_CLEAR = "LOGIN_NOTIFICATION_CLEAR"

export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"

export const ALL_LAWYERS_REQUEST = "ALL_LAWYERS_REQUEST"
export const ALL_LAWYERS_SUCCESS = "ALL_LAWYERS_SUCCESS"
export const ALL_LAWYERS_FAIL = "ALL_LAWYERS_FAIL"
export const ALL_LAWYERS_CLEAR = "ALL_LAWYERS_CLEAR"
